import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
Device/system_at32f4xx.c
""")

path = [
    cwd + '/Device',
    cwd + '/Include']

group = DefineGroup('CMSIS', src, depend = [''], CPPPATH = path)

Return('group')
