import rtconfig
from building import *

# get current directory
cwd = GetCurrentDir()

# The set of source files associated with this SConscript file.
src = Split("""
src/at32f4xx_adc.c
src/at32f4xx_can.c
src/at32f4xx_crc.c
src/at32f4xx_dbgmcu.c
src/at32f4xx_dma.c
src/at32f4xx_exti.c
src/at32f4xx_flash.c
src/at32f4xx_gpio.c
src/at32f4xx_i2c.c
src/at32f4xx_iwdg.c
src/at32f4xx_pwr.c
src/at32f4xx_rcc.c
src/at32f4xx_spi.c
src/at32f4xx_tim.c
src/at32f4xx_usart.c
src/at32f4xx_wwdg.c
src/at32f4xx_sdio.c
src/at32f4xx_acc.c
src/at32f4xx_bkp.c
src/at32f4xx_rtc.c
src/at32f4xx_ertc.c
src/at32f4xx_eth.c
src/at32f4xx_xmc.c
src/at32f4xx_comp.c
src/at32f4xx_dac.c
src/misc.c
""")

path = [
    cwd + '/inc']

CPPDEFINES = ['USE_STDPERIPH_DRIVER']

group = DefineGroup('AT32F4xx_StdPeriph_Driver', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)

Return('group')
