import os
import rtconfig
from building import *

Import('SDK_LIB')

cwd = GetCurrentDir()

# add general drivers
src = Split('''
board.c
msp/at32_msp.c
''')

path = [cwd]
path += [cwd + '/msp']

startup_path_prefix = SDK_LIB

if rtconfig.CROSS_TOOL == 'gcc':
    src += [startup_path_prefix + '/CMSIS/Device/startup/gcc/startup_at32f415kbu7-4.s']
elif rtconfig.CROSS_TOOL == 'keil':
    src += [startup_path_prefix + '/CMSIS/AT32/startup/src/mdk/startup_at32f415kbu7-4.s']
elif rtconfig.CROSS_TOOL == 'iar':
    src += [startup_path_prefix + '/CMSIS/AT32/startup/src/iar/startup_at32f415kbu7-4.s']
    
CPPDEFINES = [' AT32F415KBU7_4']
group = DefineGroup('Drivers', src, depend = [''], CPPPATH = path, CPPDEFINES = CPPDEFINES)
Return('group')
